# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

#twig:
#    form_themes:
#        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        main_config:
            #toolbar: min
            toolbar: full

    toolbars:
        configs:
            min: [ [ "Source", "-", "Save" ], "/", [ "Anchor" ], "/", [ "Maximize" ] ]
#        items:
#            document: [ "Source", "-", "Save" ]
#            link:     [ "Anchor" ]
#            tool:     [ "Maximize" ]