vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
#        products:
#            uri_prefix: /images/products
#            upload_destination: '%kernel.project_dir%/public/images/products'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        attachments:
            uri_prefix: /images/attachments
            upload_destination: '%kernel.project_dir%/public_html/uploads/items'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
